### ISSUE TITLE
Continuous test with % width & height

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#50]
I want 2 different lays depending on the width of application.   Tested in HTML, NME , and openfl

Width >= 800
4 squares with 50% width and 50% height that fill the screen.

width<800 
4 stacked squares with width 100% and 50% height.  This would cause 2 squares to be out of view.
I would like a scrollbar to appear in this case.

## Current Behavior
Issue 1: the squares are not getting correct % height so no continuous wrapping appears.  

Issue2: Resize causes crash
**OpenFL Flash and NME flash**
`ReferenceError: Error #1056: Cannot create property percentWidth on haxe.ui.containers.VBox.
	at Main/resizeMe()[C:\Users\some.guy\Desktop\Haxe\ContinioiusTest\src\Main.hx:42]
	at haxe.ui.util::EventMap/invoke()[C:\sdks\haxe3\haxe\lib\haxeui-core\git\haxe\ui\util\EventMap.hx:47]
	at haxe.ui.core::Component/dispatch()[C:\sdks\haxe3\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:826]
	at haxe.ui.core::Component/resizeComponent()[C:\sdks\haxe3\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:1051]
	at haxe.ui.core::Component/set_componentWidth()[C:\sdks\haxe3\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:1154]
	at haxe.ui.core::Component/set width()[C:\sdks\haxe3\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:1186]
	at haxe.ui.backend::ScreenBase/onContainerResize()[C:\sdks\haxe3\haxe\lib\haxeui-openfl\git\haxe\ui\backend\ScreenBase.hx:80]`

**NME windows (openfl worked like HTML5)**
`Main.hx:39: ************* resize stack  ***********
Stage.hx:464: Exception: Invalid field:percentWidth

Called from Main.resizeMe (Main.hx line 42)
Called from haxe.ui.util.EventMap.invoke (haxe/ui/util/EventMap.hx line 47)
Called from haxe.ui.core.Component.dispatch (haxe/ui/core/Component.hx line 826)
Called from haxe.ui.core.Component.resizeComponent (haxe/ui/core/Component.hx line 1051)
Called from haxe.ui.core.Component.set_componentWidth (haxe/ui/core/Component.hx line 1154)
Called from haxe.ui.core.Component.set_width (haxe/ui/core/Component.hx line 1186)
Called from haxe.ui.backend.ScreenBase.onStageResize (haxe/ui/backend/ScreenBase.hx line 75)
Called from nme.events.Listener.dispatchEvent (nme/events/EventDispatcher.hx line 32)
Called from nme.events.EventDispatcher.dispatchEvent (nme/events/EventDispatcher.hx line 140)
Called from nme.display.DisplayObject.nmeDispatchEvent (nme/display/DisplayObject.hx line 160)
Called from nme.display.Stage.onResize (nme/display/Stage.hx line 493)
Stage.hx:465:`

## Test app / minimal test case
[ContinioiusTest.zip](https://github.com/haxeui/haxeui-core/files/638137/ContinioiusTest.zip)

**Comment by hoseyjoe** [comment]
updated project after creating.

**Comment by ianharrigan** [comment]
OK, one issue is that % heights arent being honoured in continuous layouts. If i changed them for fixed heights, things work out better. 

That said that crash i still get, and its a really strange one too. Will investigate.

**Comment by ianharrigan** [comment]
Oh, i see, you are setting the properties on resize... this will have to be checked out... very possible to get into a nasty loop here.

**Comment by ianharrigan** [comment]
I believe, as per a previous conversion, this is something that is fixed now, correct?

Can you close if that is the case?

Thanks

**Comment by hoseyjoe** [comment]
This test project still throws error.  The crash occurred until we add type to variable
"var tr =" becomes  "var tr:VBox =" and then the crash goes away. I believe you think it is a Haxe bug.

**Comment by ianharrigan** [comment]
Yeah, not sure there is an easy way around this (or so ive been told)

**Comment by hoseyjoe** [comment]
what to do with this ticket.  Don like the clutter

**Comment by ianharrigan** [comment]
Leave it open for now
